### ISSUE TITLE
Header file is referred to with full (absolute) url

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/scenery#8]
I'm not sure of any way to do automatically, so it may simply be about documentation, but if you deploy the files (I did through `scp`) from one environment to another, you need to resave the theme settings to ensure the `public://scenery-custom.css` file gets the right absolute path.

**Comment by indigoxela** [comment]
Honestly, I wouldn't know of a way to help.

To be clear: the path isn't an absolute one, but the file is in the _files directory_. So, obviously outside the theme's folder.
If moving the whole website, everything's fine. If moving only the theme... tricky.

@yorkshire-pudding are you aware of any contrib theme, that found a workaround for that?

**Comment by yorkshire-pudding** [comment]
This was deploying the whole site.  It did create an absolute path and checking the code, this is what `file_create_url` (https://docs.backdropcms.org/api/backdrop/core%21includes%21file.inc/function/file_create_url/1) is meant to do.

To clarify, where I wasn't clear before, this only happens with custom images
```css
/**
 * Do not edit this file directly, your changes will be lost!
 */
.l-header {
  background-image: url(https://mysite.lndo.site/sites/mysite/files/scenery/violins-1838390_1920_0.jpg);
}
```

I'm not aware of other themes that dynamically create files like this. I don't think this is a bug per se, but possibly needs a warning if someone uploads a custom image?

For my use case, I can probably disconnect from the scenery theme so I don't have any dynamically generated files and just add the path into my theme css as a relative path.
